namespace OpenMetaverse.Rendering
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.18444
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 

    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode ("xsd", "4.0.30319.1")]
    [System.Serializable]
    [System.ComponentModel.DesignerCategory ("code")]
    [XmlRoot ("linden_skeleton", Namespace = "", IsNullable = false)]
    public partial class LindenSkeleton
    {

        Joint boneField;
        float versionField;
        bool versionFieldSpecified;
        string num_bonesField;
        string num_collision_volumesField;

        /// <remarks/>
        public Joint bone {
            get {
                return boneField;
            }
            set {
                boneField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute]
        public float version {
            get {
                return versionField;
            }
            set {
                versionField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public bool versionSpecified {
            get {
                return versionFieldSpecified;
            }
            set {
                versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute (DataType = "positiveInteger")]
        public string num_bones {
            get {
                return num_bonesField;
            }
            set {
                num_bonesField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute (DataType = "positiveInteger")]
        public string num_collision_volumes {
            get {
                return num_collision_volumesField;
            }
            set {
                num_collision_volumesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode ("xsd", "4.0.30319.1")]
    [System.Serializable ()]
    [System.ComponentModel.DesignerCategory ("code")]
    public partial class Joint : JointBase
    {

        CollisionVolume [] collision_volumeField;
        Joint [] boneField;
        float [] pivotField;

        /// <remarks/>
        [XmlElement ("collision_volume")]
        public CollisionVolume [] collision_volume {
            get {
                return collision_volumeField;
            }
            set {
                collision_volumeField = value;
            }
        }

        /// <remarks/>
        [XmlElement ("bone")]
        public Joint [] bone {
            get {
                return boneField;
            }
            set {
                boneField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute ()]
        public float [] pivot {
            get {
                return pivotField;
            }
            set {
                pivotField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode ("xsd", "4.0.30319.1")]
    [System.Serializable ()]
    [System.ComponentModel.DesignerCategory ("code")]
    public partial class CollisionVolume : JointBase
    {
    }

    /// <remarks/>
    [XmlInclude (typeof (Joint))]
    [XmlInclude (typeof (CollisionVolume))]
    [System.CodeDom.Compiler.GeneratedCode ("xsd", "4.0.30319.1")]
    [System.Serializable ()]
    [System.ComponentModel.DesignerCategory ("code")]
    public partial class JointBase
    {

        string nameField;
        float [] posField;
        float [] rotField;
        float [] scaleField;

        /// <remarks/>
        [XmlAttribute (DataType = "token")]
        public string name {
            get {
                return nameField;
            }
            set {
                nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute ()]
        public float [] pos {
            get {
                return posField;
            }
            set {
                posField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute ()]
        public float [] rot {
            get {
                return rotField;
            }
            set {
                rotField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute ()]
        public float [] scale {
            get {
                return scaleField;
            }
            set {
                scaleField = value;
            }
        }
    }
}
